origin: "Conshohocken"
destination: "Suburban Station"
n: 2
debug: 0
refresh_interval: 180

matrix:
  rows: 64
  cols: 64
  chain_length: 1
  parallel: 1
  hardware_mapping: "adafruit-hat"
  brightness: 60

display:
  logo: 5
  train: 10
  alert: 10
