origin: "Conshohocken"
destination: "Suburban Station"
n: 2
debug: 1
refresh_interval: 60 # refresh data every 60 seconds

matrix:
  rows: 64
  cols: 64
  chain_length: 1
  parallel: 1
  hardware_mapping: "adafruit-hat"
  brightness: 50

display:
  logo: 5
  train: 10
  alert: 10
