rail_lines:
  - name: "Norristown"
    origin: "Conshohocken"
    destination: "Suburban Station"
    route_id: "NOR"
    n: 2

subway:
  station: "Lombard-South"
  route_id: "B1"
  stops:
    northbound: "32139"
    southbound: "1283"
  labels:
    northbound: "NB Fern Rk"
    southbound: "SB NRG"

alerts:
  route_ids:
    - "NOR"
    - "B1"

debug: 1
refresh_interval: 60

matrix:
  rows: 64
  cols: 64
  chain_length: 1
  parallel: 1
  hardware_mapping: "adafruit-hat"
  brightness: 50

display:
  logo: 5
  train: 10
  alert: 10
